services:
  mylar:
    image: ghcr.io/linuxserver/mylar3:latest
    platform: linux/amd64
    container_name: mylar3
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - configmylar:/config
      - torrents:/comics
      - downloads:/downloads

volumes:
  configmylar: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/mylar
