services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    platform: linux/amd64
    container_name: readarr
    restart: always
    volumes:
      - configreadarr:/config
      - torrents:/torrents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  configreadarr: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/readarr